FROM registry.redhat.io/rhel9/go-toolset@sha256:f969e6a4fe53663f3fc8d0ddc17ec2fc3def2af8e68ce7061f016a598798f474 AS build-env

WORKDIR /opt/app-root/src

RUN curl -sL https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz -o /opt/app-root/src/openshift-client-linux.tar.gz && \
    tar xvf /opt/app-root/src/openshift-client-linux.tar.gz

FROM registry.access.redhat.com/ubi9/ubi@sha256:6b95efc134c2af3d45472c0a2f88e6085433df058cc210abb2bb061ac4d74359

LABEL description="This image generates the certificates for RHTAS rekor and fulcio."
LABEL io.k8s.description="This image generates the certificates for RHTAS rekor and fulcio."
LABEL io.k8s.display-name="tas-initializer-job"
LABEL io.openshift.tags="fulcio, rekor, certs"
LABEL summary="An image to run a job for provisioning ."
LABEL com.redhat.component="tas-initializer-job"

WORKDIR /tmp

COPY --from=build-env /opt/app-root/src/kubectl /usr/local/bin/kubectl
COPY --from=build-env /opt/app-root/src/oc /usr/local/bin/oc

ADD tas-initializer.sh /tmp

ENTRYPOINT ["/tmp/tas-initializer.sh"]
