FROM registry.redhat.io/openshift4/ose-cli-artifacts@sha256:9ac35a99e98e86fe942450c84c3fa78058401e74b5d5f3b61550ccd7492cefcd AS build-env
FROM registry.access.redhat.com/ubi9/ubi@sha256:6b95efc134c2af3d45472c0a2f88e6085433df058cc210abb2bb061ac4d74359

user 1001

LABEL description="This image generates the certificates for RHTAS rekor and fulcio."
LABEL io.k8s.description="This image generates the certificates for RHTAS rekor and fulcio."
LABEL io.k8s.display-name="tas-initializer-job"
LABEL io.openshift.tags="fulcio, rekor, certs"
LABEL summary="An image to run a job for provisioning ."
LABEL com.redhat.component="tas-initializer-job"

WORKDIR /tmp

COPY --from=build-env /usr/bin/kubectl /usr/local/bin/kubectl

ADD tas-initializer.sh /tmp

ENTRYPOINT ["/tmp/tas-initializer.sh"]
