{
 "title": "Sigstore Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": "tuf-system,trillian-system,sigstore,rekor-system,fulcio-system,ctlog-system,cosign"
   }
  ]
 },
 "panels": [
  { "title": "Pod Metrics per Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod status",
   "type": "table",
   "description": "Pod statistics",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"$Namespace\"} == 1",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", namespace=\"$Namespace\"}[5m])) by (pod)",
     "legendFormat": "cpu"
    },
    {
     "expr": "sum by(pod) (avg_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"$Namespace\", container!=\"\", image!=\"\"}[5m]) / 1024 / 1024)",
     "legendFormat": "memory"
    },
    {
     "expr": "sum by(pod) (avg_over_time(kubelet_volume_stats_used_bytes{namespace=\"$Namespace\"}[5m]) / 1024 / 1024)",
     "legendFormat": "memory"
    }
   ]
  },
  { "title": "Rekor Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Rekor Entries",
   "type": "stat",
   "description": "Total number of new log entries in rekor",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rekor_new_entries", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rekor api usage",
   "type": "timeseries",
   "description": "A counter for the total number of API calls made",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rekor_api_latency_count", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "Rekor api usage (per second)",
   "type": "timeseries",
   "description": "A counter for queries per second, broken down by path.",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 12 },
   "targets": [
    { "expr": "rate(rekor_qps_by_api[5m])", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "Rekor API latency bucket",
   "type": "histogram",
   "description": "total count of observations for a bucket in a histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(le) (rate(rekor_api_latency_bucket[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rekor Checkpoint publishing",
   "type": "table",
   "description": "Checkpoint publishing by shard and code",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    { "expr": "rekor_checkpoint_publish" }
   ]
  },
  { "title": "Fulcio Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Fulcio Certs",
   "type": "stat",
   "description": " The total number of certificates generated in fulcio",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fulcio_new_certs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fulcio API latency Count",
   "type": "timeseries",
   "description": "A counter for the total number of API calls made.",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(fulcio_api_latency_count[5m])",
     "legendFormat": "fulcio_api_latency_count"
    }
   ]
  },
  {
   "title": "Fulcio API latency per Bucket",
   "type": "histogram",
   "description": "Total count of observations for a bucket in a histogram\n",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(fulcio_api_latency_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Database Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SHOW GLOBAL STATUS LIKE 'Uptime';"
    }
   ]
  },
  {
   "title": "Database Size (MB)",
   "type": "stat",
   "description": "Current size of data base in (MB)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT table_schema AS 'Database',\nROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS 'Size (MB)'\nFROM information_schema.TABLES\nWHERE table_schema = 'trillian'\nGROUP BY table_schema;"
    }
   ]
  }
 ]
}