FROM quay.io/redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/cosign-cli-2-2@sha256:83e03294d6dfe8443762a735b2abb1171043cbfb93694a459e4432e520acf9a2 AS cosign-image
FROM quay.io/redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/gitsign-cli-0-8@sha256:605ee6d943acadd2ad45322f9ac49651524ffaae1dab64bfd251cddae49b86aa AS gitsign-image
FROM quay.io/redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/rekor-cli-1-3@sha256:b94954f6f82d9e5743c368a974a9d96c640e1ca7ba985fd3a86df5a989b8dd12 AS rekor-image

FROM registry.access.redhat.com/ubi9/httpd-24@sha256:965f7b03ae8f45228bad765ce47bc8956711e854213df0e4cee8623d51317b0a

RUN mkdir -p /var/www/html/clients
RUN mkdir -p /var/www/html/clients/darwin
RUN mkdir -p /var/www/html/clients/linux
RUN mkdir -p /var/www/html/clients/windows


COPY --from=cosign-image /usr/local/bin/cosign /var/www/html/clients/linux
COPY --from=cosign-image /usr/local/bin/cosign-darwin-amd64.gz /var/www/html/clients/darwin
COPY --from=cosign-image /usr/local/bin/cosign-darwin-arm64.gz /var/www/html/clients/darwin
COPY --from=cosign-image /usr/local/bin/cosign-linux-arm64.gz /var/www/html/clients/linux
COPY --from=cosign-image /usr/local/bin/cosign-linux-ppc64le.gz /var/www/html/clients/linux
COPY --from=cosign-image /usr/local/bin/cosign-linux-s390x.gz /var/www/html/clients/linux
COPY --from=cosign-image /usr/local/bin/cosign /var/www/html/clients/linux
COPY --from=cosign-image /usr/local/bin/cosign-windows-amd64.gz /var/www/html/clients/windows

RUN gzip /var/www/html/clients/linux/cosign

COPY --from=gitsign-image /usr/local/bin/gitsign_cli_darwin_amd64.gz /var/www/html/clients/darwin
COPY --from=gitsign-image /usr/local/bin/gitsign_cli_darwin_arm64.gz /var/www/html/clients/darwin
COPY --from=gitsign-image /usr/local/bin/gitsign_cli_linux_amd64.gz /var/www/html/clients/linux
COPY --from=gitsign-image /usr/local/bin/gitsign_cli_linux_arm64.gz /var/www/html/clients/linux
COPY --from=gitsign-image /usr/local/bin/gitsign_cli_linux_ppc64le.gz /var/www/html/clients/linux
COPY --from=gitsign-image /usr/local/bin/gitsign_cli_linux_s390x.gz /var/www/html/clients/linux
COPY --from=gitsign-image /usr/local/bin/gitsign_cli_windows_amd64.exe.gz /var/www/html/clients/windows

COPY --from=rekor-image /usr/local/bin/rekor_cli_darwin_amd64.gz /var/www/html/clients/darwin
COPY --from=rekor-image /usr/local/bin/rekor_cli_darwin_arm64.gz /var/www/html/clients/darwin
COPY --from=rekor-image /usr/local/bin/rekor_cli_linux_amd64.gz /var/www/html/clients/linux
COPY --from=rekor-image /usr/local/bin/rekor_cli_linux_arm64.gz /var/www/html/clients/linux
COPY --from=rekor-image /usr/local/bin/rekor_cli_linux_ppc64le.gz /var/www/html/clients/linux
COPY --from=rekor-image /usr/local/bin/rekor_cli_linux_s390x.gz /var/www/html/clients/linux
COPY --from=rekor-image /usr/local/bin/rekor_cli_windows_amd64.exe.gz /var/www/html/clients/windows

RUN   mv /var/www/html/clients/darwin/gitsign_cli_darwin_amd64.gz /var/www/html/clients/darwin/gitsign-amd64.gz && \
      mv /var/www/html/clients/darwin/gitsign_cli_darwin_arm64.gz /var/www/html/clients/darwin/gitsign-arm64.gz && \
      mv /var/www/html/clients/linux/gitsign_cli_linux_amd64.gz /var/www/html/clients/linux/gitsign-amd64.gz && \
      mv /var/www/html/clients/linux/gitsign_cli_linux_arm64.gz /var/www/html/clients/linux/gitsign-arm64.gz && \
      mv /var/www/html/clients/linux/gitsign_cli_linux_ppc64le.gz /var/www/html/clients/linux/gitsign-ppc64le.gz && \
      mv /var/www/html/clients/linux/gitsign_cli_linux_s390x.gz /var/www/html/clients/linux/gitsign-s390x.gz && \
      mv /var/www/html/clients/windows/gitsign_cli_windows_amd64.exe.gz /var/www/html/clients/windows/gitsign-amd64.gz

RUN mv /var/www/html/clients/darwin/rekor_cli_darwin_amd64.gz /var/www/html/clients/darwin/rekor-cli-amd64.gz && \
      mv /var/www/html/clients/darwin/rekor_cli_darwin_arm64.gz /var/www/html/clients/darwin/rekor-cli-arm64.gz && \
      mv /var/www/html/clients/linux/rekor_cli_linux_amd64.gz /var/www/html/clients/linux/rekor-cli-amd64.gz && \
      mv /var/www/html/clients/linux/rekor_cli_linux_arm64.gz /var/www/html/clients/linux/rekor-cli-arm64.gz && \
      mv /var/www/html/clients/linux/rekor_cli_linux_ppc64le.gz /var/www/html/clients/linux/rekor-cli-ppc64le.gz && \
      mv /var/www/html/clients/linux/rekor_cli_linux_s390x.gz /var/www/html/clients/linux/rekor-cli-s390x.gz && \
      mv /var/www/html/clients/windows/rekor_cli_windows_amd64.exe.gz /var/www/html/clients/windows/rekor-cli-amd64.gz

RUN mv /var/www/html/clients/darwin/cosign-darwin-amd64.gz /var/www/html/clients/darwin/cosign-amd64.gz && \
      mv /var/www/html/clients/windows/cosign-windows-amd64.gz /var/www/html/clients/windows/cosign-amd64.gz && \
      mv /var/www/html/clients/darwin/cosign-darwin-arm64.gz /var/www/html/clients/darwin/cosign-arm64.gz && \
      mv /var/www/html/clients/linux/cosign-linux-ppc64le.gz /var/www/html/clients/linux/cosign-ppc64le.gz && \
      mv /var/www/html/clients/linux/cosign.gz /var/www/html/clients/linux/cosign-amd64.gz && \
      mv /var/www/html/clients/linux/cosign-linux-s390x.gz /var/www/html/clients/linux/cosign-s390x.gz && \
      mv /var/www/html/clients/linux/cosign-linux-arm64.gz /var/www/html/clients/linux/cosign-arm64.gz

CMD run-httpd

LABEL \
      com.redhat.component="trusted-artifact-signer-serve-cli-container" \
      name="trusted-artifact-signer-serve-cli-container" \
      version="0.0.1" \
      summary="Red Hat serves Trusted Artifact Signer CLI binaries" \
      description="Serves Trusted Artifact Signer CLI binaries from an HTTP server" \
      io.k8s.description="Serves Trusted Artifact Signer CLI binaries from an HTTP server" \
      io.k8s.display-name="Red Hat serves Trusted Artifact Signer CLI binaries" \
      io.openshift.tags="cosign, gitsign, rekor, cli, rhtas, trusted, artifact, signer, sigstore" \
      maintainer="trusted-artifact-signer@redhat.com"
