FROM registry.access.redhat.com/ubi9/ubi:latest as builder

RUN curl -o oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz && \
    tar -xvf oc.tar.gz && \
    chmod +x oc && \
    chmod +x kubectl

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

COPY --from=builder kubectl /usr/bin/
COPY --from=builder oc /usr/bin/
