{
 "title": "Sigstore Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": "tuf-system,trillian-system,sigstore,rekor-system,fulcio-system,ctlog-system,cosign"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod status",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"$Namespace\"} == 1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"$Namespace\"}[5m]) * 100)",
     "legendFormat": "CPU Usage - {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_memory_usage_bytes{namespace=\"$Namespace\"}[5m]))",
     "legendFormat": "Memory Usage - {{ pod }}"
    }
   ]
  }
 ]
}