FROM quay.io/redhat-user-workloads/rhtas-tenant/rhtas-cli-1-0-beta/cosign@sha256:1a34ac0ee18d144b18a3f18333216e87709018acb6fea42892b5e1a17e2c8af7 AS cosign-image
FROM quay.io/redhat-user-workloads/rhtas-tenant/rhtas-cli-1-0-beta/gitsign@sha256:a8e8fb362beb5a9a10f11877f676d4d6399b4f66fe9bd15c3bc352748707b98d AS gitsign-image

FROM registry.redhat.io/rhel8/httpd-24

COPY --from=cosign-image /usr/local/bin/cosign /var/www/html/downloads/cosign
COPY --from=gitsign-image /usr/local/bin/gitsign /var/www/html/downloads/gitsign

CMD run-httpd
