{{- if and .Values.configs.fulcio.server.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configs.fulcio.server.secret.name }}
  namespace: {{ .Values.configs.fulcio.namespace }}
type: Opaque
stringData:
{{- if or .Values.configs.fulcio.server.secret.root_cert .Values.configs.fulcio.server.secret.root_cert_file }}
{{- if .Values.configs.fulcio.server.secret.root_cert }}
  cert: {{ (.Values.configs.fulcio.server.secret.root_cert | default .Values.configs.fulcio.server.secret.root_cert (.Files.Get .Values.configs.fulcio.server.secret.root_cert_file))  | toYaml | indent 2 }}
{{- end }}
{{- end }}
{{- if or .Values.configs.fulcio.server.secret.public_key .Values.configs.fulcio.server.secret.public_key_file }}
{{- if .Values.configs.fulcio.server.secret.public_key }}
  public: {{ (.Values.configs.fulcio.server.secret.public_key | default .Values.configs.fulcio.server.secret.public_key (.Files.Get .Values.configs.fulcio.server.secret.public_key_file))  | toYaml | indent 2 }}
{{- end }}
{{- end }}
{{- if or .Values.configs.fulcio.server.secret.private_key .Values.configs.fulcio.server.secret.private_key_file }}
{{- if .Values.configs.fulcio.server.secret.private_key }}
  private: {{ (.Values.configs.fulcio.server.secret.private_key | default .Values.configs.fulcio.server.secret.private_key (.Files.Get .Values.configs.fulcio.server.secret.private_key_file))  | toYaml | indent 2 }}
{{- end }}
{{- end }}
  password: {{ required "A Password is Required for the Fulcio Secret" .Values.configs.fulcio.server.secret.password }}
{{- end }}